// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.21.12
// source: jurnal.proto

package schedule_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JurnalEmpty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *JurnalEmpty) Reset() {
	*x = JurnalEmpty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jurnal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JurnalEmpty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JurnalEmpty) ProtoMessage() {}

func (x *JurnalEmpty) ProtoReflect() protoreflect.Message {
	mi := &file_jurnal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JurnalEmpty.ProtoReflect.Descriptor instead.
func (*JurnalEmpty) Descriptor() ([]byte, []int) {
	return file_jurnal_proto_rawDescGZIP(), []int{0}
}

type JurnalPrimaryKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *JurnalPrimaryKey) Reset() {
	*x = JurnalPrimaryKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jurnal_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JurnalPrimaryKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JurnalPrimaryKey) ProtoMessage() {}

func (x *JurnalPrimaryKey) ProtoReflect() protoreflect.Message {
	mi := &file_jurnal_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JurnalPrimaryKey.ProtoReflect.Descriptor instead.
func (*JurnalPrimaryKey) Descriptor() ([]byte, []int) {
	return file_jurnal_proto_rawDescGZIP(), []int{1}
}

func (x *JurnalPrimaryKey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateJurnal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId string `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	From    string `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
}

func (x *CreateJurnal) Reset() {
	*x = CreateJurnal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jurnal_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateJurnal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJurnal) ProtoMessage() {}

func (x *CreateJurnal) ProtoReflect() protoreflect.Message {
	mi := &file_jurnal_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJurnal.ProtoReflect.Descriptor instead.
func (*CreateJurnal) Descriptor() ([]byte, []int) {
	return file_jurnal_proto_rawDescGZIP(), []int{2}
}

func (x *CreateJurnal) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *CreateJurnal) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

type Jurnal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupId   string      `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	From      string      `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	To        string      `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	CreatedAt string      `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt string      `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Schedules []*Schedule `protobuf:"bytes,8,rep,name=Schedules,proto3" json:"Schedules,omitempty"`
}

func (x *Jurnal) Reset() {
	*x = Jurnal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jurnal_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Jurnal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Jurnal) ProtoMessage() {}

func (x *Jurnal) ProtoReflect() protoreflect.Message {
	mi := &file_jurnal_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Jurnal.ProtoReflect.Descriptor instead.
func (*Jurnal) Descriptor() ([]byte, []int) {
	return file_jurnal_proto_rawDescGZIP(), []int{3}
}

func (x *Jurnal) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Jurnal) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *Jurnal) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Jurnal) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Jurnal) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Jurnal) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Jurnal) GetSchedules() []*Schedule {
	if x != nil {
		return x.Schedules
	}
	return nil
}

type UpdateJurnal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupId string `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	From    string `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	To      string `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
}

func (x *UpdateJurnal) Reset() {
	*x = UpdateJurnal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jurnal_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateJurnal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateJurnal) ProtoMessage() {}

func (x *UpdateJurnal) ProtoReflect() protoreflect.Message {
	mi := &file_jurnal_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateJurnal.ProtoReflect.Descriptor instead.
func (*UpdateJurnal) Descriptor() ([]byte, []int) {
	return file_jurnal_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateJurnal) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateJurnal) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *UpdateJurnal) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *UpdateJurnal) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type GetListJurnalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset int64  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit  int64  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Search string `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
}

func (x *GetListJurnalRequest) Reset() {
	*x = GetListJurnalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jurnal_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListJurnalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListJurnalRequest) ProtoMessage() {}

func (x *GetListJurnalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jurnal_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListJurnalRequest.ProtoReflect.Descriptor instead.
func (*GetListJurnalRequest) Descriptor() ([]byte, []int) {
	return file_jurnal_proto_rawDescGZIP(), []int{5}
}

func (x *GetListJurnalRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetListJurnalRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetListJurnalRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type GetListJurnalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count   int64     `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Jurnals []*Jurnal `protobuf:"bytes,2,rep,name=Jurnals,proto3" json:"Jurnals,omitempty"`
}

func (x *GetListJurnalResponse) Reset() {
	*x = GetListJurnalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jurnal_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListJurnalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListJurnalResponse) ProtoMessage() {}

func (x *GetListJurnalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jurnal_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListJurnalResponse.ProtoReflect.Descriptor instead.
func (*GetListJurnalResponse) Descriptor() ([]byte, []int) {
	return file_jurnal_proto_rawDescGZIP(), []int{6}
}

func (x *GetListJurnalResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetListJurnalResponse) GetJurnals() []*Jurnal {
	if x != nil {
		return x.Jurnals
	}
	return nil
}

var File_jurnal_proto protoreflect.FileDescriptor

var file_jurnal_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6a, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10,
	0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x1a, 0x0e, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x0d, 0x0a, 0x0b, 0x4a, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22,
	0x22, 0x0a, 0x10, 0x4a, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x50, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79,
	0x4b, 0x65, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x3d, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4a, 0x75, 0x72,
	0x6e, 0x61, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x72,
	0x6f, 0x6d, 0x22, 0xcf, 0x01, 0x0a, 0x06, 0x4a, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x19, 0x0a,
	0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02,
	0x74, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x1d, 0x0a, 0x0a,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x38, 0x0a, 0x09, 0x53, 0x63,
	0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x09, 0x53, 0x63, 0x68, 0x65, 0x64,
	0x75, 0x6c, 0x65, 0x73, 0x22, 0x5d, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4a, 0x75,
	0x72, 0x6e, 0x61, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66,
	0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x74, 0x6f, 0x22, 0x5c, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x4a, 0x75,
	0x72, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f,
	0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x22, 0x61, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x4a, 0x75, 0x72, 0x6e,
	0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x32, 0x0a, 0x07, 0x4a, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x4a, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x52, 0x07, 0x4a, 0x75, 0x72,
	0x6e, 0x61, 0x6c, 0x73, 0x32, 0x93, 0x03, 0x0a, 0x0d, 0x4a, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x44, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x12, 0x1e, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4a, 0x75, 0x72, 0x6e, 0x61, 0x6c,
	0x1a, 0x18, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x4a, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x07,
	0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x44, 0x12, 0x22, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75,
	0x6c, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4a, 0x75, 0x72, 0x6e, 0x61,
	0x6c, 0x50, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x4b, 0x65, 0x79, 0x1a, 0x18, 0x2e, 0x73, 0x63,
	0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4a,
	0x75, 0x72, 0x6e, 0x61, 0x6c, 0x22, 0x00, 0x12, 0x5c, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x26, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x4a, 0x75, 0x72,
	0x6e, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x73, 0x63, 0x68,
	0x65, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x4a, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x44, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12,
	0x1e, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4a, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x1a,
	0x18, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x4a, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x06, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x22, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4a, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x50,
	0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x4b, 0x65, 0x79, 0x1a, 0x1d, 0x2e, 0x73, 0x63, 0x68, 0x65,
	0x64, 0x75, 0x6c, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4a, 0x75, 0x72,
	0x6e, 0x61, 0x6c, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x1b, 0x5a, 0x19, 0x67, 0x65,
	0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_jurnal_proto_rawDescOnce sync.Once
	file_jurnal_proto_rawDescData = file_jurnal_proto_rawDesc
)

func file_jurnal_proto_rawDescGZIP() []byte {
	file_jurnal_proto_rawDescOnce.Do(func() {
		file_jurnal_proto_rawDescData = protoimpl.X.CompressGZIP(file_jurnal_proto_rawDescData)
	})
	return file_jurnal_proto_rawDescData
}

var file_jurnal_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_jurnal_proto_goTypes = []interface{}{
	(*JurnalEmpty)(nil),           // 0: schedule_service.JurnalEmpty
	(*JurnalPrimaryKey)(nil),      // 1: schedule_service.JurnalPrimaryKey
	(*CreateJurnal)(nil),          // 2: schedule_service.CreateJurnal
	(*Jurnal)(nil),                // 3: schedule_service.Jurnal
	(*UpdateJurnal)(nil),          // 4: schedule_service.UpdateJurnal
	(*GetListJurnalRequest)(nil),  // 5: schedule_service.GetListJurnalRequest
	(*GetListJurnalResponse)(nil), // 6: schedule_service.GetListJurnalResponse
	(*Schedule)(nil),              // 7: schedule_service.Schedule
}
var file_jurnal_proto_depIdxs = []int32{
	7, // 0: schedule_service.Jurnal.Schedules:type_name -> schedule_service.Schedule
	3, // 1: schedule_service.GetListJurnalResponse.Jurnals:type_name -> schedule_service.Jurnal
	2, // 2: schedule_service.JurnalService.Create:input_type -> schedule_service.CreateJurnal
	1, // 3: schedule_service.JurnalService.GetByID:input_type -> schedule_service.JurnalPrimaryKey
	5, // 4: schedule_service.JurnalService.GetList:input_type -> schedule_service.GetListJurnalRequest
	4, // 5: schedule_service.JurnalService.Update:input_type -> schedule_service.UpdateJurnal
	1, // 6: schedule_service.JurnalService.Delete:input_type -> schedule_service.JurnalPrimaryKey
	3, // 7: schedule_service.JurnalService.Create:output_type -> schedule_service.Jurnal
	3, // 8: schedule_service.JurnalService.GetByID:output_type -> schedule_service.Jurnal
	6, // 9: schedule_service.JurnalService.GetList:output_type -> schedule_service.GetListJurnalResponse
	3, // 10: schedule_service.JurnalService.Update:output_type -> schedule_service.Jurnal
	0, // 11: schedule_service.JurnalService.Delete:output_type -> schedule_service.JurnalEmpty
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_jurnal_proto_init() }
func file_jurnal_proto_init() {
	if File_jurnal_proto != nil {
		return
	}
	file_schedule_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_jurnal_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JurnalEmpty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jurnal_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JurnalPrimaryKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jurnal_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateJurnal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jurnal_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Jurnal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jurnal_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateJurnal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jurnal_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListJurnalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jurnal_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListJurnalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_jurnal_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jurnal_proto_goTypes,
		DependencyIndexes: file_jurnal_proto_depIdxs,
		MessageInfos:      file_jurnal_proto_msgTypes,
	}.Build()
	File_jurnal_proto = out.File
	file_jurnal_proto_rawDesc = nil
	file_jurnal_proto_goTypes = nil
	file_jurnal_proto_depIdxs = nil
}
