// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: schedule.proto

package schedule_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ScheduleService_Create_FullMethodName                 = "/schedule_service.ScheduleService/Create"
	ScheduleService_GetByID_FullMethodName                = "/schedule_service.ScheduleService/GetByID"
	ScheduleService_GetList_FullMethodName                = "/schedule_service.ScheduleService/GetList"
	ScheduleService_Update_FullMethodName                 = "/schedule_service.ScheduleService/Update"
	ScheduleService_Delete_FullMethodName                 = "/schedule_service.ScheduleService/Delete"
	ScheduleService_GetScheduleReport_FullMethodName      = "/schedule_service.ScheduleService/GetScheduleReport"
	ScheduleService_GetScheduleMonthReport_FullMethodName = "/schedule_service.ScheduleService/GetScheduleMonthReport"
)

// ScheduleServiceClient is the client API for ScheduleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScheduleServiceClient interface {
	Create(ctx context.Context, in *CreateSchedule, opts ...grpc.CallOption) (*Schedule, error)
	GetByID(ctx context.Context, in *SchedulePrimaryKey, opts ...grpc.CallOption) (*Schedule, error)
	GetList(ctx context.Context, in *GetListScheduleRequest, opts ...grpc.CallOption) (*GetListScheduleResponse, error)
	Update(ctx context.Context, in *UpdateSchedule, opts ...grpc.CallOption) (*Schedule, error)
	Delete(ctx context.Context, in *SchedulePrimaryKey, opts ...grpc.CallOption) (*ScheduleEmpty, error)
	GetScheduleReport(ctx context.Context, in *ScheduleReportRequest, opts ...grpc.CallOption) (*ScheduleReportResponse, error)
	GetScheduleMonthReport(ctx context.Context, in *ScheduleReportRequest, opts ...grpc.CallOption) (*ScheduleReportResponse, error)
}

type scheduleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewScheduleServiceClient(cc grpc.ClientConnInterface) ScheduleServiceClient {
	return &scheduleServiceClient{cc}
}

func (c *scheduleServiceClient) Create(ctx context.Context, in *CreateSchedule, opts ...grpc.CallOption) (*Schedule, error) {
	out := new(Schedule)
	err := c.cc.Invoke(ctx, ScheduleService_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleServiceClient) GetByID(ctx context.Context, in *SchedulePrimaryKey, opts ...grpc.CallOption) (*Schedule, error) {
	out := new(Schedule)
	err := c.cc.Invoke(ctx, ScheduleService_GetByID_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleServiceClient) GetList(ctx context.Context, in *GetListScheduleRequest, opts ...grpc.CallOption) (*GetListScheduleResponse, error) {
	out := new(GetListScheduleResponse)
	err := c.cc.Invoke(ctx, ScheduleService_GetList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleServiceClient) Update(ctx context.Context, in *UpdateSchedule, opts ...grpc.CallOption) (*Schedule, error) {
	out := new(Schedule)
	err := c.cc.Invoke(ctx, ScheduleService_Update_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleServiceClient) Delete(ctx context.Context, in *SchedulePrimaryKey, opts ...grpc.CallOption) (*ScheduleEmpty, error) {
	out := new(ScheduleEmpty)
	err := c.cc.Invoke(ctx, ScheduleService_Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleServiceClient) GetScheduleReport(ctx context.Context, in *ScheduleReportRequest, opts ...grpc.CallOption) (*ScheduleReportResponse, error) {
	out := new(ScheduleReportResponse)
	err := c.cc.Invoke(ctx, ScheduleService_GetScheduleReport_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleServiceClient) GetScheduleMonthReport(ctx context.Context, in *ScheduleReportRequest, opts ...grpc.CallOption) (*ScheduleReportResponse, error) {
	out := new(ScheduleReportResponse)
	err := c.cc.Invoke(ctx, ScheduleService_GetScheduleMonthReport_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScheduleServiceServer is the server API for ScheduleService service.
// All implementations must embed UnimplementedScheduleServiceServer
// for forward compatibility
type ScheduleServiceServer interface {
	Create(context.Context, *CreateSchedule) (*Schedule, error)
	GetByID(context.Context, *SchedulePrimaryKey) (*Schedule, error)
	GetList(context.Context, *GetListScheduleRequest) (*GetListScheduleResponse, error)
	Update(context.Context, *UpdateSchedule) (*Schedule, error)
	Delete(context.Context, *SchedulePrimaryKey) (*ScheduleEmpty, error)
	GetScheduleReport(context.Context, *ScheduleReportRequest) (*ScheduleReportResponse, error)
	GetScheduleMonthReport(context.Context, *ScheduleReportRequest) (*ScheduleReportResponse, error)
	mustEmbedUnimplementedScheduleServiceServer()
}

// UnimplementedScheduleServiceServer must be embedded to have forward compatible implementations.
type UnimplementedScheduleServiceServer struct {
}

func (UnimplementedScheduleServiceServer) Create(context.Context, *CreateSchedule) (*Schedule, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedScheduleServiceServer) GetByID(context.Context, *SchedulePrimaryKey) (*Schedule, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByID not implemented")
}
func (UnimplementedScheduleServiceServer) GetList(context.Context, *GetListScheduleRequest) (*GetListScheduleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetList not implemented")
}
func (UnimplementedScheduleServiceServer) Update(context.Context, *UpdateSchedule) (*Schedule, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedScheduleServiceServer) Delete(context.Context, *SchedulePrimaryKey) (*ScheduleEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedScheduleServiceServer) GetScheduleReport(context.Context, *ScheduleReportRequest) (*ScheduleReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetScheduleReport not implemented")
}
func (UnimplementedScheduleServiceServer) GetScheduleMonthReport(context.Context, *ScheduleReportRequest) (*ScheduleReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetScheduleMonthReport not implemented")
}
func (UnimplementedScheduleServiceServer) mustEmbedUnimplementedScheduleServiceServer() {}

// UnsafeScheduleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScheduleServiceServer will
// result in compilation errors.
type UnsafeScheduleServiceServer interface {
	mustEmbedUnimplementedScheduleServiceServer()
}

func RegisterScheduleServiceServer(s grpc.ServiceRegistrar, srv ScheduleServiceServer) {
	s.RegisterService(&ScheduleService_ServiceDesc, srv)
}

func _ScheduleService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSchedule)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScheduleService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServiceServer).Create(ctx, req.(*CreateSchedule))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduleService_GetByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchedulePrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServiceServer).GetByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScheduleService_GetByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServiceServer).GetByID(ctx, req.(*SchedulePrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduleService_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServiceServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScheduleService_GetList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServiceServer).GetList(ctx, req.(*GetListScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduleService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSchedule)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScheduleService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServiceServer).Update(ctx, req.(*UpdateSchedule))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduleService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchedulePrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScheduleService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServiceServer).Delete(ctx, req.(*SchedulePrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduleService_GetScheduleReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServiceServer).GetScheduleReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScheduleService_GetScheduleReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServiceServer).GetScheduleReport(ctx, req.(*ScheduleReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduleService_GetScheduleMonthReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServiceServer).GetScheduleMonthReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScheduleService_GetScheduleMonthReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServiceServer).GetScheduleMonthReport(ctx, req.(*ScheduleReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ScheduleService_ServiceDesc is the grpc.ServiceDesc for ScheduleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScheduleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "schedule_service.ScheduleService",
	HandlerType: (*ScheduleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ScheduleService_Create_Handler,
		},
		{
			MethodName: "GetByID",
			Handler:    _ScheduleService_GetByID_Handler,
		},
		{
			MethodName: "GetList",
			Handler:    _ScheduleService_GetList_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ScheduleService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ScheduleService_Delete_Handler,
		},
		{
			MethodName: "GetScheduleReport",
			Handler:    _ScheduleService_GetScheduleReport_Handler,
		},
		{
			MethodName: "GetScheduleMonthReport",
			Handler:    _ScheduleService_GetScheduleMonthReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "schedule.proto",
}
